[theme]
primaryColor = "#f63366"
# backgroundColor = "#10344b"
backgroundColor = "#F0F8FF"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#E0E7FF"
textColor = "#333333"
font = "sans serif"

[server]
enableStaticServing = true
